dist: bionic
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"

# Pipfile is only for Python3.7
install:
    - if [[ $TRAVIS_PYTHON_VERSION != 3.7 ]]; then rm Pipfile.lock; fi
    - pip3 install pipenv
    - pipenv install
    - pipenv run python3 -m spacy download en_core_web_sm

script: pipenv run pytest

notifications:
    email: false
