dist: bionic
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install poetry
    - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then rm poetry.lock; fi
    - poetry install
    - poetry run python -m spacy download en_core_web_sm

script: poetry run pytest

notifications:
    email: false
